# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My GradeSource
description: > # this means to ignore newlines until "baseurl:"
  Feeling frustrated that you have to open a web browser every time you want to check your course status?
  Here is your time-saver! Try our "My GradeSource" to check your grade easily!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mygradesource.github.io/" # the base hostname & protocol for your site
github_username: mygradesource

# Build settings
markdown: kramdown
